version: "2.4"

services:
  
  app:
    build: ./docker/app
    container_name: app
    restart: always
    ports:
      - 44444:44444
      - 44444:44444/udp

  mysql:
    build: ./docker/mysql
    container_name: mysql
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    command: mysqld --sql_mode=""

volumes:
  mysql-data:
